name: PR Pipeline

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref ||  github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    name: Stand aktualisieren
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Letzte Commit-Message laden
        id: last_commit
        run: |
          last_commit_msg=$(git log -1 --pretty=%s)
          echo "lastcommit=$last_commit_msg" >> $GITHUB_ENV

      - name: Abhängigkeiten laden
        run: npm ci

      - name: Code formatieren
        if: >-
              ${{
              !contains(env.lastcommit, '🎨 Code formatiert') &&
              !contains(env.lastcommit, '📝 README generiert')
              }}
        run: npm run format-all

      - name: Add formatting-commit
        if: >-
          ${{
          !contains(env.lastcommit, '🎨 Code formatiert') &&
          !contains(env.lastcommit, '📝 README generiert')
          }}
        run: |
          git config --global user.name 'OpenFoxes Maintenance Bot'
          git config --global user.email 'openfoxes@bono-fox.de'
          git checkout ${{ github.event.pull_request.head.ref }}
          git add .
          git diff-index --quiet ${{ github.event.pull_request.head.ref }} || {
          git commit -m "🎨 Code formatiert"
          git push origin ${{ github.event.pull_request.head.ref }}
          }

      - name: README generieren
        if: "!contains(env.lastcommit, '📝 README generiert')"
        run: npm run generate-readme

      - name: Add README-commit
        if: "!contains(env.lastcommit, '📝 README generiert')"
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          git add .
          git diff-index --quiet ${{ github.event.pull_request.head.ref }} || {
          git commit -m "📝 README generiert"
          git push origin ${{ github.event.pull_request.head.ref }}
          }
